local function note(id, timeValue, lane, groan, pose, lightCue, crowdCue)
    return {
        id = id,
        time = timeValue,
        lane = lane,
        groan = groan,
        pose = pose,
        lightCue = lightCue,
        crowdCue = crowdCue,
    }
end

return {
    Id = "MallBalladButWrong",
    Title = "Mall Ballad But Wrong",
    Artist = "Groan Tube Hero",
    AudioId = "rbxassetid://0",
    BPM = 140,
    Offset = 0,
    Duration = 39.0,
    Sections = {
        { name = "Intro", start = 0, finish = 7.5 },
        { name = "Verse", start = 7.5, finish = 18.0 },
        { name = "Chorus", start = 18.0, finish = 28.0 },
        { name = "Bridge", start = 28.0, finish = 33.0 },
        { name = "Finale", start = 33.0, finish = 39.0 },
    },
    Notes = {
        note("mbw-01", 1.0, 1, "Soft Groan", "Lean Left", "Teal", "Cheer"),
        note("mbw-02", 1.7, 4, "Normal Groan", "Lean Right", "Yellow", "Clap"),
        note("mbw-03", 2.3, 2, "Normal Groan", "Chest Puff", "Teal", "Cheer"),
        note("mbw-04", 2.9, 3, "Normal Groan", "Wide Stance", "Yellow", "Clap"),
        note("mbw-05", 3.7, 1, "Soft Groan", "Head Tilt", "Teal", "Cheer"),
        note("mbw-06", 4.2, 3, "Normal Groan", "Quick Point", "Yellow", "Clap"),
        note("mbw-07", 5.0, 2, "Normal Groan", "Stomp", "Teal", "Cheer"),
        note("mbw-08", 5.8, 4, "Normal Groan", "Shoulder Roll", "Yellow", "Clap"),
        note("mbw-09", 7.8, 1, "Normal Groan", "Lean Left", "Teal", "Cheer"),
        note("mbw-10", 8.4, 2, "Normal Groan", "Lean Right", "Yellow", "Clap"),
        note("mbw-11", 9.0, 3, "Normal Groan", "Chest Puff", "Teal", "Cheer"),
        note("mbw-12", 9.6, 4, "Normal Groan", "Wide Stance", "Yellow", "Clap"),
        note("mbw-13", 10.2, 1, "Normal Groan", "Head Tilt", "Teal", "Cheer"),
        note("mbw-14", 11.0, 2, "Normal Groan", "Quick Point", "Yellow", "Clap"),
        note("mbw-15", 11.7, 3, "Normal Groan", "Stomp", "Teal", "Cheer"),
        note("mbw-16", 12.3, 4, "Normal Groan", "Shoulder Roll", "Yellow", "Clap"),
        note("mbw-17", 13.0, 1, "Normal Groan", "Arm Sweep", "Teal", "Cheer"),
        note("mbw-18", 13.7, 3, "Normal Groan", "Raised Chin", "Yellow", "Clap"),
        note("mbw-19", 15.0, 2, "Normal Groan", "Lean Left", "Teal", "Cheer"),
        note("mbw-20", 16.0, 4, "Normal Groan", "Lean Right", "Yellow", "Clap"),
        note("mbw-21", 18.4, 1, "Big Groan", "Stage Lean", "Gold", "Encore"),
        note("mbw-22", 19.1, 2, "Big Groan", "Raised Chin", "Teal", "Cheer"),
        note("mbw-23", 20.0, 3, "Big Groan", "Lean Right", "Yellow", "Clap"),
        note("mbw-24", 21.0, 4, "Big Groan", "Wide Stance", "Gold", "Encore"),
        note("mbw-25", 22.0, 1, "Big Groan", "Arm Sweep", "Teal", "Cheer"),
        note("mbw-26", 23.5, 2, "Big Groan", "Chest Puff", "Yellow", "Clap"),
        note("mbw-27", 25.0, 3, "Big Groan", "Head Tilt", "Gold", "Encore"),
        note("mbw-28", 26.4, 4, "Big Groan", "Quick Point", "Teal", "Cheer"),
        note("mbw-29", 28.8, 1, "Bridge Groan", "Soft Lean", "Yellow", "Clap"),
        note("mbw-30", 30.0, 4, "Bridge Groan", "Soft Lean", "Teal", "Cheer"),
        note("mbw-31", 33.8, 2, "Final Groan", "Final Pose", "Gold", "Encore"),
        note("mbw-32", 37.0, 3, "Final Groan", "Final Pose", "Gold", "Encore"),
    },
}
