local function note(id, timeValue, lane, groan, pose, lightCue, crowdCue)
    return {
        id = id,
        time = timeValue,
        lane = lane,
        groan = groan,
        pose = pose,
        lightCue = lightCue,
        crowdCue = crowdCue,
    }
end

return {
    Id = "NeonGroan",
    Title = "Neon Groan",
    Artist = "Groan Tube Hero",
    AudioId = "rbxassetid://0",
    BPM = 108,
    Offset = 0,
    Duration = 31.5,
    Sections = {
        { name = "Intro", start = 0, finish = 8.0 },
        { name = "Verse", start = 8.0, finish = 17.0 },
        { name = "Chorus", start = 17.0, finish = 27.0 },
        { name = "Outro", start = 27.0, finish = 31.5 },
    },
    Notes = {
        note("ng-01", 1.5, 1, "Soft Groan", "Lean Left", "Cyan", "Cheer"),
        note("ng-02", 2.3, 2, "Soft Groan", "Lean Right", "Blue", "Clap"),
        note("ng-03", 3.1, 3, "Clean Groan", "Chest Puff", "Purple", "Cheer"),
        note("ng-04", 3.9, 4, "Clean Groan", "Wide Stance", "Cyan", "Clap"),
        note("ng-05", 5.0, 2, "Soft Groan", "Head Tilt", "Blue", "Cheer"),
        note("ng-06", 6.0, 3, "Clean Groan", "Quick Point", "Purple", "Clap"),
        note("ng-07", 7.2, 1, "Soft Groan", "Stomp", "Cyan", "Cheer"),
        note("ng-08", 8.4, 4, "Clean Groan", "Shoulder Roll", "White", "Clap"),
        note("ng-09", 9.4, 2, "Normal Groan", "Lean Left", "Blue", "Cheer"),
        note("ng-10", 10.2, 3, "Normal Groan", "Lean Right", "Purple", "Clap"),
        note("ng-11", 11.0, 1, "Normal Groan", "Chest Puff", "Cyan", "Cheer"),
        note("ng-12", 12.0, 4, "Normal Groan", "Wide Stance", "White", "Clap"),
        note("ng-13", 13.0, 2, "Normal Groan", "Head Tilt", "Blue", "Cheer"),
        note("ng-14", 14.0, 3, "Normal Groan", "Quick Point", "Purple", "Clap"),
        note("ng-15", 15.0, 1, "Normal Groan", "Stomp", "Cyan", "Cheer"),
        note("ng-16", 16.0, 4, "Normal Groan", "Shoulder Roll", "White", "Clap"),
        note("ng-17", 17.5, 1, "Big Groan", "Stage Lean", "Cyan", "Cheer"),
        note("ng-18", 18.4, 2, "Big Groan", "Raised Chin", "Blue", "Clap"),
        note("ng-19", 19.0, 3, "Big Groan", "Lean Right", "Purple", "Cheer"),
        note("ng-20", 20.0, 4, "Big Groan", "Wide Stance", "White", "Encore"),
        note("ng-21", 21.2, 1, "Big Groan", "Arm Sweep", "Cyan", "Cheer"),
        note("ng-22", 23.0, 3, "Big Groan", "Chest Puff", "Purple", "Clap"),
        note("ng-23", 25.0, 2, "Big Groan", "Head Tilt", "Blue", "Cheer"),
        note("ng-24", 27.4, 4, "Final Groan", "Final Pose", "Gold", "Encore"),
    },
}
