local function note(id, timeValue, lane, groan, pose, lightCue, crowdCue)
    return {
        id = id,
        time = timeValue,
        lane = lane,
        groan = groan,
        pose = pose,
        lightCue = lightCue,
        crowdCue = crowdCue,
    }
end

return {
    Id = "RomanticTubeDisaster",
    Title = "Romantic Tube Disaster",
    Artist = "Groan Tube Hero",
    AudioId = "rbxassetid://0",
    BPM = 128,
    Offset = 0,
    Duration = 35.0,
    Sections = {
        { name = "Intro", start = 0, finish = 8.0 },
        { name = "Verse", start = 8.0, finish = 17.5 },
        { name = "Chorus", start = 17.5, finish = 28.0 },
        { name = "Bridge", start = 28.0, finish = 32.0 },
        { name = "Finale", start = 32.0, finish = 35.0 },
    },
    Notes = {
        note("rtd-01", 1.4, 1, "Soft Groan", "Lean Left", "Pink", "Cheer"),
        note("rtd-02", 2.0, 3, "Normal Groan", "Lean Right", "Purple", "Clap"),
        note("rtd-03", 2.7, 2, "Normal Groan", "Chest Puff", "Pink", "Cheer"),
        note("rtd-04", 3.4, 4, "Clean Groan", "Wide Stance", "Blue", "Clap"),
        note("rtd-05", 4.5, 1, "Soft Groan", "Head Tilt", "Pink", "Cheer"),
        note("rtd-06", 5.1, 2, "Normal Groan", "Quick Point", "Purple", "Clap"),
        note("rtd-07", 6.0, 4, "Normal Groan", "Stomp", "Blue", "Cheer"),
        note("rtd-08", 7.0, 3, "Clean Groan", "Shoulder Roll", "Pink", "Clap"),
        note("rtd-09", 8.6, 1, "Normal Groan", "Lean Left", "Purple", "Cheer"),
        note("rtd-10", 9.3, 2, "Normal Groan", "Lean Right", "Pink", "Clap"),
        note("rtd-11", 10.0, 3, "Normal Groan", "Chest Puff", "Blue", "Cheer"),
        note("rtd-12", 11.0, 4, "Normal Groan", "Wide Stance", "Purple", "Clap"),
        note("rtd-13", 12.0, 1, "Normal Groan", "Head Tilt", "Pink", "Cheer"),
        note("rtd-14", 13.1, 2, "Normal Groan", "Quick Point", "Blue", "Clap"),
        note("rtd-15", 14.2, 3, "Normal Groan", "Stomp", "Purple", "Cheer"),
        note("rtd-16", 15.3, 4, "Normal Groan", "Shoulder Roll", "Pink", "Clap"),
        note("rtd-17", 17.8, 1, "Big Groan", "Stage Lean", "Gold", "Encore"),
        note("rtd-18", 18.6, 2, "Big Groan", "Raised Chin", "Pink", "Cheer"),
        note("rtd-19", 19.2, 3, "Big Groan", "Lean Right", "Purple", "Clap"),
        note("rtd-20", 20.0, 4, "Big Groan", "Wide Stance", "Blue", "Cheer"),
        note("rtd-21", 21.0, 1, "Big Groan", "Arm Sweep", "Pink", "Clap"),
        note("rtd-22", 22.2, 4, "Big Groan", "Chest Puff", "Purple", "Cheer"),
        note("rtd-23", 24.0, 2, "Big Groan", "Head Tilt", "Blue", "Clap"),
        note("rtd-24", 25.0, 3, "Big Groan", "Quick Point", "Pink", "Cheer"),
        note("rtd-25", 28.6, 1, "Bridge Groan", "Soft Lean", "Purple", "Clap"),
        note("rtd-26", 29.4, 4, "Bridge Groan", "Soft Lean", "Pink", "Cheer"),
        note("rtd-27", 31.5, 2, "Final Groan", "Final Pose", "Gold", "Encore"),
        note("rtd-28", 33.8, 3, "Final Groan", "Final Pose", "Gold", "Encore"),
    },
}
